## Download the files listed below from https://github.com/datacharmer/test_db to `scripts` folder
###     - load_departments.dump
###     - load_dept_emp.dump
###     - load_dept_manager.dump
###     - load_titles.dump
###     - load_salaries1.dump
###     - load_salaries2.dump
###     - load_salaries3.dump

version: "3.4"

services: 
  
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    volumes: 
      - "mysql_data:/tmp/mysql/employees-sample" 
      - "./scripts:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
      - MYSQL_ROOT_PASSWORD=Pa$$w0rd
      - MYSQL_DATABASE=employees
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"
    environment:
      -   ADMINER_DEFAULT_SERVER=mysql

volumes:
  mysql_data:
    driver: local      